// Generated by scripts/gen_ring_device.py --cores 32. Do not edit by hand;
// change the script and regenerate instead.

// RUN: dataflow-scheduler-opt %s | dataflow-scheduler-opt

// A 32-core ring device. Each core has the ring_device DDR <-> L1 DMA
// units and one corelet with the sample_device L1 -> L1LU -> SFU -> L1SU -> L1
// chain. Every core's MNISU can inject into, and its MNILU can eject from, a
// ring stop. The stops are linked into a bidirectional ring in core order:
// clockwise links go from stop K to stop K+1, counter-clockwise links from
// stop K to stop K-1 (modulo 32).
//
// Ports of each ring stop:
//   0: cw_in    1: ccw_in    2: inject    3: cw_out    4: ccw_out    5: eject
//
// A stop forwards traffic in the direction it arrived in, and may drop a copy
// at its own core on the way (cw_in -> {cw_out, eject}, ccw_in -> {ccw_out,
// eject}). Injected traffic leaves in either direction but never ejects
// locally, and nothing turns around.
//
// The corelet group has a kind, like the core group, so that views that
// flatten groups by kind (the routing graph) treat every corelet as an
// instance of one class rather than as a distinct group of its own.

#DDR = {
  kind = "DDR",
  size = 1073741824 //1GB
}
#DDR_MNILU = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}
#MNISU_DDR = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}

#L1 = {
  kind = "L1",
  size = 1048576 //1MB
}
#MNILU = {
  kind = "MNILU",
  ktdf_arch.features = {
    ktdf_arch.feature.load = {
      word_size = #ktdf_arch.map<"DDR" = 64, "L1" = 64>,
      access_granularity = #ktdf_arch.map<
        "DDR" = [{size_in_words = 1, align_in_words = 1}],
        "L1" = [{size_in_words = 1, align_in_words = 1}]
      >
    }
  },
  dataflow_scheduler.double_buffer_last
}
#MNILU_L1 = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}
#MNISU = {
  kind = "MNISU",
  ktdf_arch.features = {
    ktdf_arch.feature.store = {
      word_size = #ktdf_arch.map<"DDR" = 64, "L1" = 64>,
      access_granularity = #ktdf_arch.map<
        "DDR" = [{size_in_words = 1, align_in_words = 1}],
        "L1" = [{size_in_words = 1, align_in_words = 1}]
      >
    }
  },
  dataflow_scheduler.double_buffer_last
}
#L1_MNISU = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}

#SFU = {
  kind = "SFU",
  ktdf_arch.features = {
    ktdf_arch.feature.compute,
    ktdf_arch.feature.simd = { lanes = #ktdf_arch.map<f16 = 64> }
  }
}
#SFU_REG = {
  kind = "SFU_REG",
  size = 2048 //2KB
}

#L1LU = {
  kind = "L1LU",
  ktdf_arch.features = {
    ktdf_arch.feature.load = {
      access_granularity = #ktdf_arch.map<
        "L1" = [
          {size_in_words = 64, align_in_words = 64},
          {size_in_words = 2, align_in_words = 2}
        ]
      >
    },
    ktdf_arch.feature.simd = { splat, zero_pad }
  }
}
#L1LU_CORE_FIFO = {
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}
#L1LU_SUBCORE_FIFO = {
  ktdf_arch.transfer_granularity = array<i64: 64, 2>,
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}

#L1SU = {
  kind = "L1SU",
  ktdf_arch.features = {
    ktdf_arch.feature.store = {
      access_granularity = #ktdf_arch.map<
        "L1" = [
          {size_in_words = 64, align_in_words = 64},
          {size_in_words = 2, align_in_words = 2}
        ]
      >
    }
  }
}
#L1SU_CORE_FIFO = {
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}
#L1SU_SUBCORE_FIFO = {
  ktdf_arch.transfer_granularity = array<i64: 64, 2>,
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}

#RING_STOP = {
  kind = "RING_STOP",
  connectivity = sparse<[[0, 3], [0, 5], [1, 4], [1, 5], [2, 3], [2, 4]], true> : tensor<6x6xi1>
}
#RING_CW = { kind = "RING_CW" }
#RING_CCW = { kind = "RING_CCW" }
ktdf_arch.device @ring32_device {
  %ddr = memory #DDR

  // Core 0.
  %mnilu0, %mnisu0 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 1.
  %mnilu1, %mnisu1 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 2.
  %mnilu2, %mnisu2 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 3.
  %mnilu3, %mnisu3 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 4.
  %mnilu4, %mnisu4 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 5.
  %mnilu5, %mnisu5 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 6.
  %mnilu6, %mnisu6 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 7.
  %mnilu7, %mnisu7 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 8.
  %mnilu8, %mnisu8 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 9.
  %mnilu9, %mnisu9 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 10.
  %mnilu10, %mnisu10 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 11.
  %mnilu11, %mnisu11 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 12.
  %mnilu12, %mnisu12 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 13.
  %mnilu13, %mnisu13 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 14.
  %mnilu14, %mnisu14 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 15.
  %mnilu15, %mnisu15 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 16.
  %mnilu16, %mnisu16 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 17.
  %mnilu17, %mnisu17 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 18.
  %mnilu18, %mnisu18 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 19.
  %mnilu19, %mnisu19 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 20.
  %mnilu20, %mnisu20 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 21.
  %mnilu21, %mnisu21 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 22.
  %mnilu22, %mnisu22 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 23.
  %mnilu23, %mnisu23 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 24.
  %mnilu24, %mnisu24 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 25.
  %mnilu25, %mnisu25 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 26.
  %mnilu26, %mnisu26 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 27.
  %mnilu27, %mnisu27 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 28.
  %mnilu28, %mnisu28 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 29.
  %mnilu29, %mnisu29 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 30.
  %mnilu30, %mnisu30 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Core 31.
  %mnilu31, %mnisu31 = group { kind = "core" } share(%ddr) {
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group { kind = "corelet" } share(%l1) {
      %sfu = group { kind = "SFU_Block" } share() {
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      } -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }
    yield %mnilu, %mnisu
  } -> exec_unit, exec_unit

  // Ring stops, one per core.
  %s0:6 = switch[6] #RING_STOP
  %s1:6 = switch[6] #RING_STOP
  %s2:6 = switch[6] #RING_STOP
  %s3:6 = switch[6] #RING_STOP
  %s4:6 = switch[6] #RING_STOP
  %s5:6 = switch[6] #RING_STOP
  %s6:6 = switch[6] #RING_STOP
  %s7:6 = switch[6] #RING_STOP
  %s8:6 = switch[6] #RING_STOP
  %s9:6 = switch[6] #RING_STOP
  %s10:6 = switch[6] #RING_STOP
  %s11:6 = switch[6] #RING_STOP
  %s12:6 = switch[6] #RING_STOP
  %s13:6 = switch[6] #RING_STOP
  %s14:6 = switch[6] #RING_STOP
  %s15:6 = switch[6] #RING_STOP
  %s16:6 = switch[6] #RING_STOP
  %s17:6 = switch[6] #RING_STOP
  %s18:6 = switch[6] #RING_STOP
  %s19:6 = switch[6] #RING_STOP
  %s20:6 = switch[6] #RING_STOP
  %s21:6 = switch[6] #RING_STOP
  %s22:6 = switch[6] #RING_STOP
  %s23:6 = switch[6] #RING_STOP
  %s24:6 = switch[6] #RING_STOP
  %s25:6 = switch[6] #RING_STOP
  %s26:6 = switch[6] #RING_STOP
  %s27:6 = switch[6] #RING_STOP
  %s28:6 = switch[6] #RING_STOP
  %s29:6 = switch[6] #RING_STOP
  %s30:6 = switch[6] #RING_STOP
  %s31:6 = switch[6] #RING_STOP

  // Each core injects into, and ejects from, its own stop.
  datapath %mnisu0 to %s0#2 : exec_unit, port
  datapath %s0#5 to %mnilu0 : port, exec_unit
  datapath %mnisu1 to %s1#2 : exec_unit, port
  datapath %s1#5 to %mnilu1 : port, exec_unit
  datapath %mnisu2 to %s2#2 : exec_unit, port
  datapath %s2#5 to %mnilu2 : port, exec_unit
  datapath %mnisu3 to %s3#2 : exec_unit, port
  datapath %s3#5 to %mnilu3 : port, exec_unit
  datapath %mnisu4 to %s4#2 : exec_unit, port
  datapath %s4#5 to %mnilu4 : port, exec_unit
  datapath %mnisu5 to %s5#2 : exec_unit, port
  datapath %s5#5 to %mnilu5 : port, exec_unit
  datapath %mnisu6 to %s6#2 : exec_unit, port
  datapath %s6#5 to %mnilu6 : port, exec_unit
  datapath %mnisu7 to %s7#2 : exec_unit, port
  datapath %s7#5 to %mnilu7 : port, exec_unit
  datapath %mnisu8 to %s8#2 : exec_unit, port
  datapath %s8#5 to %mnilu8 : port, exec_unit
  datapath %mnisu9 to %s9#2 : exec_unit, port
  datapath %s9#5 to %mnilu9 : port, exec_unit
  datapath %mnisu10 to %s10#2 : exec_unit, port
  datapath %s10#5 to %mnilu10 : port, exec_unit
  datapath %mnisu11 to %s11#2 : exec_unit, port
  datapath %s11#5 to %mnilu11 : port, exec_unit
  datapath %mnisu12 to %s12#2 : exec_unit, port
  datapath %s12#5 to %mnilu12 : port, exec_unit
  datapath %mnisu13 to %s13#2 : exec_unit, port
  datapath %s13#5 to %mnilu13 : port, exec_unit
  datapath %mnisu14 to %s14#2 : exec_unit, port
  datapath %s14#5 to %mnilu14 : port, exec_unit
  datapath %mnisu15 to %s15#2 : exec_unit, port
  datapath %s15#5 to %mnilu15 : port, exec_unit
  datapath %mnisu16 to %s16#2 : exec_unit, port
  datapath %s16#5 to %mnilu16 : port, exec_unit
  datapath %mnisu17 to %s17#2 : exec_unit, port
  datapath %s17#5 to %mnilu17 : port, exec_unit
  datapath %mnisu18 to %s18#2 : exec_unit, port
  datapath %s18#5 to %mnilu18 : port, exec_unit
  datapath %mnisu19 to %s19#2 : exec_unit, port
  datapath %s19#5 to %mnilu19 : port, exec_unit
  datapath %mnisu20 to %s20#2 : exec_unit, port
  datapath %s20#5 to %mnilu20 : port, exec_unit
  datapath %mnisu21 to %s21#2 : exec_unit, port
  datapath %s21#5 to %mnilu21 : port, exec_unit
  datapath %mnisu22 to %s22#2 : exec_unit, port
  datapath %s22#5 to %mnilu22 : port, exec_unit
  datapath %mnisu23 to %s23#2 : exec_unit, port
  datapath %s23#5 to %mnilu23 : port, exec_unit
  datapath %mnisu24 to %s24#2 : exec_unit, port
  datapath %s24#5 to %mnilu24 : port, exec_unit
  datapath %mnisu25 to %s25#2 : exec_unit, port
  datapath %s25#5 to %mnilu25 : port, exec_unit
  datapath %mnisu26 to %s26#2 : exec_unit, port
  datapath %s26#5 to %mnilu26 : port, exec_unit
  datapath %mnisu27 to %s27#2 : exec_unit, port
  datapath %s27#5 to %mnilu27 : port, exec_unit
  datapath %mnisu28 to %s28#2 : exec_unit, port
  datapath %s28#5 to %mnilu28 : port, exec_unit
  datapath %mnisu29 to %s29#2 : exec_unit, port
  datapath %s29#5 to %mnilu29 : port, exec_unit
  datapath %mnisu30 to %s30#2 : exec_unit, port
  datapath %s30#5 to %mnilu30 : port, exec_unit
  datapath %mnisu31 to %s31#2 : exec_unit, port
  datapath %s31#5 to %mnilu31 : port, exec_unit

  // Clockwise ring: stop K -> stop K+1.
  datapath #RING_CW %s0#3 to %s1#0 : port, port
  datapath #RING_CW %s1#3 to %s2#0 : port, port
  datapath #RING_CW %s2#3 to %s3#0 : port, port
  datapath #RING_CW %s3#3 to %s4#0 : port, port
  datapath #RING_CW %s4#3 to %s5#0 : port, port
  datapath #RING_CW %s5#3 to %s6#0 : port, port
  datapath #RING_CW %s6#3 to %s7#0 : port, port
  datapath #RING_CW %s7#3 to %s8#0 : port, port
  datapath #RING_CW %s8#3 to %s9#0 : port, port
  datapath #RING_CW %s9#3 to %s10#0 : port, port
  datapath #RING_CW %s10#3 to %s11#0 : port, port
  datapath #RING_CW %s11#3 to %s12#0 : port, port
  datapath #RING_CW %s12#3 to %s13#0 : port, port
  datapath #RING_CW %s13#3 to %s14#0 : port, port
  datapath #RING_CW %s14#3 to %s15#0 : port, port
  datapath #RING_CW %s15#3 to %s16#0 : port, port
  datapath #RING_CW %s16#3 to %s17#0 : port, port
  datapath #RING_CW %s17#3 to %s18#0 : port, port
  datapath #RING_CW %s18#3 to %s19#0 : port, port
  datapath #RING_CW %s19#3 to %s20#0 : port, port
  datapath #RING_CW %s20#3 to %s21#0 : port, port
  datapath #RING_CW %s21#3 to %s22#0 : port, port
  datapath #RING_CW %s22#3 to %s23#0 : port, port
  datapath #RING_CW %s23#3 to %s24#0 : port, port
  datapath #RING_CW %s24#3 to %s25#0 : port, port
  datapath #RING_CW %s25#3 to %s26#0 : port, port
  datapath #RING_CW %s26#3 to %s27#0 : port, port
  datapath #RING_CW %s27#3 to %s28#0 : port, port
  datapath #RING_CW %s28#3 to %s29#0 : port, port
  datapath #RING_CW %s29#3 to %s30#0 : port, port
  datapath #RING_CW %s30#3 to %s31#0 : port, port
  datapath #RING_CW %s31#3 to %s0#0 : port, port

  // Counter-clockwise ring: stop K -> stop K-1.
  datapath #RING_CCW %s0#4 to %s31#1 : port, port
  datapath #RING_CCW %s1#4 to %s0#1 : port, port
  datapath #RING_CCW %s2#4 to %s1#1 : port, port
  datapath #RING_CCW %s3#4 to %s2#1 : port, port
  datapath #RING_CCW %s4#4 to %s3#1 : port, port
  datapath #RING_CCW %s5#4 to %s4#1 : port, port
  datapath #RING_CCW %s6#4 to %s5#1 : port, port
  datapath #RING_CCW %s7#4 to %s6#1 : port, port
  datapath #RING_CCW %s8#4 to %s7#1 : port, port
  datapath #RING_CCW %s9#4 to %s8#1 : port, port
  datapath #RING_CCW %s10#4 to %s9#1 : port, port
  datapath #RING_CCW %s11#4 to %s10#1 : port, port
  datapath #RING_CCW %s12#4 to %s11#1 : port, port
  datapath #RING_CCW %s13#4 to %s12#1 : port, port
  datapath #RING_CCW %s14#4 to %s13#1 : port, port
  datapath #RING_CCW %s15#4 to %s14#1 : port, port
  datapath #RING_CCW %s16#4 to %s15#1 : port, port
  datapath #RING_CCW %s17#4 to %s16#1 : port, port
  datapath #RING_CCW %s18#4 to %s17#1 : port, port
  datapath #RING_CCW %s19#4 to %s18#1 : port, port
  datapath #RING_CCW %s20#4 to %s19#1 : port, port
  datapath #RING_CCW %s21#4 to %s20#1 : port, port
  datapath #RING_CCW %s22#4 to %s21#1 : port, port
  datapath #RING_CCW %s23#4 to %s22#1 : port, port
  datapath #RING_CCW %s24#4 to %s23#1 : port, port
  datapath #RING_CCW %s25#4 to %s24#1 : port, port
  datapath #RING_CCW %s26#4 to %s25#1 : port, port
  datapath #RING_CCW %s27#4 to %s26#1 : port, port
  datapath #RING_CCW %s28#4 to %s27#1 : port, port
  datapath #RING_CCW %s29#4 to %s28#1 : port, port
  datapath #RING_CCW %s30#4 to %s29#1 : port, port
  datapath #RING_CCW %s31#4 to %s30#1 : port, port
}
