#!/usr/bin/env python3

#
# Copyright 2026 The KTIR Scheduler Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Emit a ring device with one corelet per core.

Each core has the ring_device.mlir DDR <-> L1 DMA units and a single corelet
with the sample_device.mlir L1LU -> SFU -> L1SU chain. One ring stop per core,
linked into a bidirectional ring in core order.

Usage:
  scripts/gen_ring_device.py --cores 32 > test/Dialect/KTDFArch/ring32_device.mlir
"""

import argparse

HEADER = """\
// Generated by scripts/gen_ring_device.py --cores {cores}. Do not edit by hand;
// change the script and regenerate instead.

// RUN: dataflow-scheduler-opt %s | dataflow-scheduler-opt

// A {cores}-core ring device. Each core has the ring_device DDR <-> L1 DMA
// units and one corelet with the sample_device L1 -> L1LU -> SFU -> L1SU -> L1
// chain. Every core's MNISU can inject into, and its MNILU can eject from, a
// ring stop. The stops are linked into a bidirectional ring in core order:
// clockwise links go from stop K to stop K+1, counter-clockwise links from
// stop K to stop K-1 (modulo {cores}).
//
// Ports of each ring stop:
//   0: cw_in    1: ccw_in    2: inject    3: cw_out    4: ccw_out    5: eject
//
// A stop forwards traffic in the direction it arrived in, and may drop a copy
// at its own core on the way (cw_in -> {{cw_out, eject}}, ccw_in -> {{ccw_out,
// eject}}). Injected traffic leaves in either direction but never ejects
// locally, and nothing turns around.
//
// The corelet group has a kind, like the core group, so that views that
// flatten groups by kind (the routing graph) treat every corelet as an
// instance of one class rather than as a distinct group of its own.
"""

ATTRIBUTES = """\
#DDR = {
  kind = "DDR",
  size = 1073741824 //1GB
}
#DDR_MNILU = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}
#MNISU_DDR = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}

#L1 = {
  kind = "L1",
  size = 1048576 //1MB
}
#MNILU = {
  kind = "MNILU",
  ktdf_arch.features = {
    ktdf_arch.feature.load = {
      word_size = #ktdf_arch.map<"DDR" = 64, "L1" = 64>,
      access_granularity = #ktdf_arch.map<
        "DDR" = [{size_in_words = 1, align_in_words = 1}],
        "L1" = [{size_in_words = 1, align_in_words = 1}]
      >
    }
  },
  dataflow_scheduler.double_buffer_last
}
#MNILU_L1 = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}
#MNISU = {
  kind = "MNISU",
  ktdf_arch.features = {
    ktdf_arch.feature.store = {
      word_size = #ktdf_arch.map<"DDR" = 64, "L1" = 64>,
      access_granularity = #ktdf_arch.map<
        "DDR" = [{size_in_words = 1, align_in_words = 1}],
        "L1" = [{size_in_words = 1, align_in_words = 1}]
      >
    }
  },
  dataflow_scheduler.double_buffer_last
}
#L1_MNISU = {
  ktdf_arch.transfer_granularity = array<i64: 64> //64B
}

#SFU = {
  kind = "SFU",
  ktdf_arch.features = {
    ktdf_arch.feature.compute,
    ktdf_arch.feature.simd = { lanes = #ktdf_arch.map<f16 = 64> }
  }
}
#SFU_REG = {
  kind = "SFU_REG",
  size = 2048 //2KB
}

#L1LU = {
  kind = "L1LU",
  ktdf_arch.features = {
    ktdf_arch.feature.load = {
      access_granularity = #ktdf_arch.map<
        "L1" = [
          {size_in_words = 64, align_in_words = 64},
          {size_in_words = 2, align_in_words = 2}
        ]
      >
    },
    ktdf_arch.feature.simd = { splat, zero_pad }
  }
}
#L1LU_CORE_FIFO = {
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}
#L1LU_SUBCORE_FIFO = {
  ktdf_arch.transfer_granularity = array<i64: 64, 2>,
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}

#L1SU = {
  kind = "L1SU",
  ktdf_arch.features = {
    ktdf_arch.feature.store = {
      access_granularity = #ktdf_arch.map<
        "L1" = [
          {size_in_words = 64, align_in_words = 64},
          {size_in_words = 2, align_in_words = 2}
        ]
      >
    }
  }
}
#L1SU_CORE_FIFO = {
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}
#L1SU_SUBCORE_FIFO = {
  ktdf_arch.transfer_granularity = array<i64: 64, 2>,
  ktdf_arch.features = { ktdf_arch.feature.queue = { depth = 16, ordered } }
}

#RING_STOP = {
  kind = "RING_STOP",
  connectivity = sparse<[[0, 3], [0, 5], [1, 4], [1, 5], [2, 3], [2, 4]], true> : tensor<6x6xi1>
}
#RING_CW = { kind = "RING_CW" }
#RING_CCW = { kind = "RING_CCW" }
"""

CORE = """\
  // Core {k}.
  %mnilu{k}, %mnisu{k} = group {{ kind = "core" }} share(%ddr) {{
    %l1 = memory #L1
    %mnilu = exec_unit #MNILU
    %mnisu = exec_unit #MNISU

    datapath #DDR_MNILU %ddr to %mnilu : memory, exec_unit
    datapath #MNILU_L1 %mnilu to %l1 : exec_unit, memory
    datapath #L1_MNISU %l1 to %mnisu : memory, exec_unit
    datapath #MNISU_DDR %mnisu to %ddr : exec_unit, memory

    group {{ kind = "corelet" }} share(%l1) {{
      %sfu = group {{ kind = "SFU_Block" }} share() {{
        %sfu_reg = memory #SFU_REG
        %sfu_unit = exec_unit #SFU
        yield %sfu_unit
      }} -> exec_unit
      %l1lu = exec_unit #L1LU
      %l1su = exec_unit #L1SU

      datapath #L1LU_CORE_FIFO %l1 to %l1lu : memory, exec_unit
      datapath #L1LU_SUBCORE_FIFO %l1lu to %sfu : exec_unit, exec_unit
      datapath #L1SU_SUBCORE_FIFO %sfu to %l1su : exec_unit, exec_unit
      datapath #L1SU_CORE_FIFO %l1su to %l1 : exec_unit, memory
    }}
    yield %mnilu, %mnisu
  }} -> exec_unit, exec_unit
"""


def emit(cores: int) -> str:
    out = [HEADER.format(cores=cores), "\n", ATTRIBUTES]
    out.append(f"ktdf_arch.device @ring{cores}_device {{\n")
    out.append("  %ddr = memory #DDR\n\n")
    out.append("\n".join(CORE.format(k=k) for k in range(cores)))

    out.append("\n  // Ring stops, one per core.\n")
    for k in range(cores):
        out.append(f"  %s{k}:6 = switch[6] #RING_STOP\n")

    out.append("\n  // Each core injects into, and ejects from, its own stop.\n")
    for k in range(cores):
        out.append(f"  datapath %mnisu{k} to %s{k}#2 : exec_unit, port\n")
        out.append(f"  datapath %s{k}#5 to %mnilu{k} : port, exec_unit\n")

    out.append("\n  // Clockwise ring: stop K -> stop K+1.\n")
    for k in range(cores):
        out.append(
            f"  datapath #RING_CW %s{k}#3 to %s{(k + 1) % cores}#0 : port, port\n"
        )

    out.append("\n  // Counter-clockwise ring: stop K -> stop K-1.\n")
    for k in range(cores):
        out.append(
            f"  datapath #RING_CCW %s{k}#4 to %s{(k - 1) % cores}#1 : port, port\n"
        )

    out.append("}\n")
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cores", type=int, default=32, help="number of cores")
    args = parser.parse_args()
    if args.cores < 2:
        parser.error("a ring needs at least two cores")
    print(emit(args.cores), end="")


if __name__ == "__main__":
    main()
